; Maps keyboard shortcuts from P-Malt to QWERTY.
; Jak Crow
; Created: 2017/05/21

;┌─────────────────────────────────────────────────────────────────────────────
;│ AHK SETUP
;└─────────────────────────────────────────────────────────────────────────────
#NoEnv
SetBatchLines -1
ListLines Off
#SingleInstance force
SetTitleMatchMode RegEx
#Hotstring EndChars ( )[]{}:`;",.?!_=%
#UseHook

Suspend On

+.::Send <
+,::Send >
^y::Send ^w
^p::Send ^e
^b::Send ^r
^;::Send ^t
^-::Send ^y
^m::Send ^i
^l::Send ^o
^z::Send ^p
^s::Send ^f
^i::Send ^s
^n::Send ^d
^f::Send ^g
^d::Send ^h
^h::Send ^j
^t::Send ^k
^r::Send ^l
^o::Send ^;
^x::Send ^z
^j::Send ^x
^g::Send ^v
^.::Send ^b
^,::Send ^n
^v::Send ^m
^w::Send ^,
^k::Send ^.
!y::Send !w
!p::Send !e
!b::Send !r
!;::Send !t
!-::Send !y
!m::Send !i
!l::Send !o
!z::Send !p
!i::Send !s
!n::Send !d
!s::Send !f
!f::Send !g
!d::Send !h
!h::Send !j
!t::Send !k
!r::Send !l
!o::Send !;
!x::Send !z
!j::Send !x
!g::Send !v
!.::Send !b
!,::Send !n
!v::Send !m
!w::Send !,
!k::Send !.
#y::Send #w
#p::Send #e
#b::Send #r
#;::Send #t
#-::Send #y
#m::Send #i
#l::Send #o
#z::Send #p
#i::Send #s
#n::Send #d
#s::Send #f
#f::Send #g
#d::Send #h
#h::Send #j
#t::Send #k
#r::Send #l
#o::Send #;
#x::Send #z
#j::Send #x
#g::Send #v
#.::Send #b
#,::Send #n
#v::Send #m
#w::Send #,
#k::Send #.
^!y::Send ^!w
^!p::Send ^!e
^!b::Send ^!r
^!;::Send ^!t
^!-::Send ^!y
^!m::Send ^!i
^!l::Send ^!o
^!z::Send ^!p
^!i::Send ^!s
^!n::Send ^!d
^!s::Send ^!f
^!f::Send ^!g
^!d::Send ^!h
^!h::Send ^!j
^!t::Send ^!k
^!r::Send ^!l
^!o::Send ^!;
^!x::Send ^!z
^!j::Send ^!x
^!g::Send ^!v
^!.::Send ^!b
^!,::Send ^!n
^!v::Send ^!m
^!w::Send ^!,
^!k::Send ^!.
^+y::Send ^+w
^+p::Send ^+e
^+b::Send ^+r
^+;::Send ^+t
^+-::Send ^+y
^+m::Send ^+i
^+l::Send ^+o
^+z::Send ^+p
^+i::Send ^+s
^+n::Send ^+d
^+s::Send ^+f
^+f::Send ^+g
^+d::Send ^+h
^+h::Send ^+j
^+t::Send ^+k
^+r::Send ^+l
^+o::Send ^+;
^+x::Send ^+z
^+j::Send ^+x
^+g::Send ^+v
^+.::Send ^+b
^+,::Send ^+n
^+v::Send ^+m
^+w::Send ^+,
^+k::Send ^+.
^#y::Send ^#w
^#p::Send ^#e
^#b::Send ^#r
^#;::Send ^#t
^#-::Send ^#y
^#m::Send ^#i
^#l::Send ^#o
^#z::Send ^#p
^#i::Send ^#s
^#n::Send ^#d
^#s::Send ^#f
^#f::Send ^#g
^#d::Send ^#h
^#h::Send ^#j
^#t::Send ^#k
^#r::Send ^#l
^#o::Send ^#;
^#x::Send ^#z
^#j::Send ^#x
^#g::Send ^#v
^#.::Send ^#b
^#,::Send ^#n
^#v::Send ^#m
^#w::Send ^#,
^#k::Send ^#.
!+y::Send !+w
!+p::Send !+e
!+b::Send !+r
!+;::Send !+t
!+-::Send !+y
!+m::Send !+i
!+l::Send !+o
!+z::Send !+p
!+i::Send !+s
!+n::Send !+d
!+s::Send !+f
!+f::Send !+g
!+d::Send !+h
!+h::Send !+j
!+t::Send !+k
!+r::Send !+l
!+o::Send !+;
!+x::Send !+z
!+j::Send !+x
!+g::Send !+v
!+.::Send !+b
!+,::Send !+n
!+v::Send !+m
!+w::Send !+,
!+k::Send !+.
!#y::Send !#w
!#p::Send !#e
!#b::Send !#r
!#;::Send !#t
!#-::Send !#y
!#m::Send !#i
!#l::Send !#o
!#z::Send !#p
!#i::Send !#s
!#n::Send !#d
!#s::Send !#f
!#f::Send !#g
!#d::Send !#h
!#h::Send !#j
!#t::Send !#k
!#r::Send !#l
!#o::Send !#;
!#x::Send !#z
!#j::Send !#x
!#g::Send !#v
!#.::Send !#b
!#,::Send !#n
!#v::Send !#m
!#w::Send !#,
!#k::Send !#.
+#y::Send +#w
+#p::Send +#e
+#b::Send +#r
+#;::Send +#t
+#-::Send +#y
+#m::Send +#i
+#l::Send +#o
+#z::Send +#p
+#i::Send +#s
+#n::Send +#d
+#s::Send +#f
+#f::Send +#g
+#d::Send +#h
+#h::Send +#j
+#t::Send +#k
+#r::Send +#l
+#o::Send +#;
+#x::Send +#z
+#j::Send +#x
+#g::Send +#v
+#.::Send +#b
+#,::Send +#n
+#v::Send +#m
+#w::Send +#,
+#k::Send +#.
^!#y::Send ^!#w
^!#p::Send ^!#e
^!#b::Send ^!#r
^!#;::Send ^!#t
^!#-::Send ^!#y
^!#m::Send ^!#i
^!#l::Send ^!#o
^!#z::Send ^!#p
^!#i::Send ^!#s
^!#n::Send ^!#d
^!#s::Send ^!#f
^!#f::Send ^!#g
^!#d::Send ^!#h
^!#h::Send ^!#j
^!#t::Send ^!#k
^!#r::Send ^!#l
^!#o::Send ^!#;
^!#x::Send ^!#z
^!#j::Send ^!#x
^!#g::Send ^!#v
^!#.::Send ^!#b
^!#,::Send ^!#n
^!#v::Send ^!#m
^!#w::Send ^!#,
^!#k::Send ^!#.
^+#y::Send ^+#w
^+#p::Send ^+#e
^+#b::Send ^+#r
^+#;::Send ^+#t
^+#-::Send ^+#y
^+#m::Send ^+#i
^+#l::Send ^+#o
^+#z::Send ^+#p
^+#i::Send ^+#s
^+#n::Send ^+#d
^+#s::Send ^+#f
^+#f::Send ^+#g
^+#d::Send ^+#h
^+#h::Send ^+#j
^+#t::Send ^+#k
^+#r::Send ^+#l
^+#o::Send ^+#;
^+#x::Send ^+#z
^+#j::Send ^+#x
^+#g::Send ^+#v
^+#.::Send ^+#b
^+#,::Send ^+#n
^+#v::Send ^+#m
^+#w::Send ^+#,
^+#k::Send ^+#.
^!+y::Send ^!+w
^!+p::Send ^!+e
^!+b::Send ^!+r
^!+;::Send ^!+t
^!+-::Send ^!+y
^!+m::Send ^!+i
^!+l::Send ^!+o
^!+z::Send ^!+p
^!+i::Send ^!+s
^!+n::Send ^!+d
^!+s::Send ^!+f
^!+f::Send ^!+g
^!+d::Send ^!+h
^!+h::Send ^!+j
^!+t::Send ^!+k
^!+r::Send ^!+l
^!+o::Send ^!+;
^!+x::Send ^!+z
^!+j::Send ^!+x
^!+g::Send ^!+v
^!+.::Send ^!+b
^!+v::Send ^!+m
^!+,::Send ^!+n
^!+w::Send ^!+,
^!+k::Send ^!+.
^!+#y::Send ^!+#w
^!+#p::Send ^!+#e
^!+#b::Send ^!+#r
^!+#;::Send ^!+#t
^!+#-::Send ^!+#y
^!+#m::Send ^!+#i
^!+#l::Send ^!+#o
^!+#z::Send ^!+#p
^!+#i::Send ^!+#s
^!+#n::Send ^!+#d
^!+#s::Send ^!+#f
^!+#f::Send ^!+#g
^!+#d::Send ^!+#h
^!+#h::Send ^!+#j
^!+#t::Send ^!+#k
^!+#r::Send ^!+#l
^!+#o::Send ^!+#;
^!+#x::Send ^!+#z
^!+#j::Send ^!+#x
^!+#g::Send ^!+#v
^!+#.::Send ^!+#b
^!+#,::Send ^!+#n
^!+#v::Send ^!+#m
^!+#w::Send ^!+#,
^!+#k::Send ^!+#.
